version: "3.7"
services:
  logger:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.{{.Name}}
        labels: "io.baselime.service,io.baselime.namespace"
    labels:
      io.baselime.service: "my_service"
      io.baselime.namespace: "my_namespace"
  fluentd:
    image: fluentd:latest
    volumes:
      - ./conf:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluent.conf